name: "datanode01"
token: "abc"

ip: "127.0.0.1"
port: 20001

log_path: "logs"
root_path: "data"

disk_size: 1024

name_node_ip: "127.0.0.1"
name_node_port: 20000

paths: ["/zxt", "/root"]

# ["path,uid,gid"]
# ["/zxt,2,2"]
init_paths: ["/,1,1,40755", "/root,1,1,40700", "/zxt,2,2,40700"]
