name: "datanode01"
token: "abc"

ip: "0.0.0.0"
port: 20001

log_path: "logs"
root_path: "data"

disk_size: 1024

buffer_size: 4194304
max_msg_size: 2097152

name_node_ip: "127.0.0.1"
name_node_port: 20000

paths: ["/zxt", "/root"]

# ["path,uid,gid"]
# ["/zxt,2,2"]
init_paths: ["/root,1,1", "/zxt,2,2"]
